version: '3'
services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - datavol:/var/lib/mysql
      - ./mysql-confd:/etc/mysql/conf.d
  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/aquarist
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
    - MYSQL_HOST=db
    - MYSQL_PASSWORD=password
volumes:
  datavol: